name: Jekyll Build Pull Requests

on: 
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.8'
    - name: Debug Gem and Bundler Environment
      run: |
        gem environment
        bundle env
    - name: Update Bundler
      run: gem install bundler
    - name: Install dependencies
      run: bundle install
    - name: Build site
      run: bundle exec jekyll build
